@startuml

actor User as U
participant MainProgramm as S
participant Lexer as L
participant Verificator as V


activate S

U -> S : ./compiloWhile <file>.while

S -> L : generateAST()
activate L
create AST 
L -> AST  : creation
L -> AST : filling the AST
activate AST
alt error making the AST
L -> S : error while making the\n AST at line xxx
S -> U : report error 
deactivate AST
else

L --> S : return the AST
deactivate L



S -> V : checkAll(Tree AST)
activate V
V -> V : test1()
activate V
deactivate V
V -> V : test2()
activate V
V --> S : Unknown variable/function at line xxx
deactivate V
S -> U : report error
deactivate V

end

deactivate S
@enduml
